language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - py test_orders.py
  - coverage run test_orders.py
  #- nosetests -v --with-coverage --cover-package=app

after_success:
  - coveralls