sudo: false

language: python

python:
  - 3.6

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - coverage run v1/tests/test_orders.py
  - python v1/tests/test_orders.py

after_success:
  - codecov
  - coveralls