language: python

python:
  - 3.6
  - 3.7

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install codecov


script: 
  - pytest v1/tests/test_orders.py
  -  py.test --cov-report html --cov [v1] --verbose

after_success:
  - coverage report -m
  - codecov
  - coveralls