sudo: false

language: python

python:
  - 3.6

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - python v1/test_orders.py
  - coverage run v1/test_orders.py
  - nosetests --with-coverage --cover-package=tests

after_success:
  - codecov
  - coveralls