language: python

python:
  - 3.6

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

script: 
  - pytest -v --cov main --cov-report term-missing
  - coverage report
  - coveralls
  
after_success:
  - codecov