language: python

python:
  - 3.6

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install nose

script: 
  - pytest --cov=main
  - coverage run main/tests/test_orders.py
  
after_success:
  - coverage report -m
  - codecov
  - coveralls